### ISSUE TITLE
Error in read.table(file = file,...) : more columns than column names

### ISSUE THREAD

**Issue by PietroD** [csoneson/alevinQC#11]
Hi 
I am trying to run alevinQC dev version on the output of salmon 1.0.0.
`checkAlevinInputFiles` returns "v0.14", but when calling `alevinQCReport` it throws the error 

`Reading Alevin output files...
Quitting from lines 31-34 (alevinReport.Rmd) 
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  more columns than column names`

What can I do?
Thanks
Pietro

**Comment by csoneson** [comment]
Could you provide the code that you used to run `alevin`? 
Also, could you please run 
```
alevin <- readAlevinQC(baseDir = baseDir)
```
and post the output (that's the function that returns the error above)?

**Comment by PietroD** [comment]
`salmon alevin -lISR -1 R1.fastq.gz R2.fastq.gz --chromiumV3 -i index -p 16 --dumpFeatures --dumpUmiGraph -o alevin_output --tgMap txp2gene.tsv`

Just found out that the code creating the problem is the one reading the file `featureDump.txt`.

Here is the header of my `featureDump.txt` file:

<img width="1785" alt="Schermata 2020-01-25 alle 17 04 58" src="https://user-images.githubusercontent.com/33426755/73123857-e05b2200-3f94-11ea-8588-6a8ea49303fd.png">

The error from `alevin <- readAlevinQC(baseDir = baseDir)` is the same reported above.

Thanks for the quick reply!

**Comment by k3yavi** [comment]
Hi @PietroD ,

Thanks for reporting this.
May I ask do you have any specific requirements for UMI graphs ? The flag --dumpUmiGraph along with --dumpFeatures enables an internal feature of reporting Arborescence count. Can you try running Alevin without --dumpUmiGraph or another option is to ignore columns after column 9. I think it has been fixed in 1.1 but might have to recheck.

**Comment by PietroD** [comment]
Hi @k3yavi 

If I run alevin without the --dumpUmiGraph flag, the file raw_cb_frequency.txt is not generated, so when I run `checkAlevinInputFiles` it throws the error 

`Error in checkAlevinInputFiles(baseDir = baseDir) : 
  Input directory not compatible with Salmon v0.14, the following required file(s) are missing or malformed:
alevin_output_NoUmigraphs//alevin/raw_cb_frequency.txt`

**Comment by k3yavi** [comment]
Hi @PietroD ,

Are you sure it's --dumpUmiGraph or not including --dumpFeatures would skip raw_cb_freq file ?
Another thing you can try is updating salmon to latest version of 1.1, that might fix things as well.

**Comment by csoneson** [comment]
I agree with Avi that the best is to update Salmon to v1.1, where this is fixed. However, I just pushed a possible fix to the `extbarcodes` branch of alevinQC - could you try and see if this works (or if you would be willing to share the first lines of your `featureDump.txt` file in the screen shot above, so I can test it on my side)? Basically, it's just checking if the file can be cleanly read, and if not, reads just the first columns (up to the number of column names).

**Comment by PietroD** [comment]
> Hi @PietroD ,
> 
> Are you sure it's --dumpUmiGraph or not including --dumpFeatures would skip raw_cb_freq file ?
> Another thing you can try is updating salmon to latest version of 1.1, that might fix things as well.

Sorry you are right, removing --dumpUmiGraph solves the problem, that is, the raw_cb_frequency.txt file is created and loaded correctly with the `readAlevinQC` function.

Unfortunately I am on a cluster so updating Salmon is not an immediate option.



> I agree with Avi that the best is to update Salmon to v1.1, where this is fixed. However, I just pushed a possible fix to the `extbarcodes` branch of alevinQC - could you try and see if this works (or if you would be willing to share the first lines of your `featureDump.txt` file in the screen shot above, so I can test it on my side)? Basically, it's just checking if the file can be cleanly read, and if not, reads just the first columns (up to the number of column names).

I still have not tried the possible fix, but I can attach here a sample of the `featureDump.txt` file with strange Arborescence column.

[featureDump_mod2.txt](https://github.com/csoneson/alevinQC/files/4116927/featureDump_mod2.txt)

**Comment by csoneson** [comment]
Thanks @PietroD - the fix seems to work for your file above. Of course, you won't need it if you run alevin without `--dumpUmiGraph`, but I'll keep it there in case it happens to someone else.

**Comment by PietroD** [comment]
Good to have it in case someone wants to run AlevinQC after Salmon with the UMI graph option.
Thanks again to both of you for the help!

**Comment by csoneson** [comment]
Fixed in #12
