### ISSUE TITLE
what is the definition of "cell barcode collapsing" in elvinQC R package

### ISSUE THREAD

**Issue by yueli8** [csoneson/alevinQC#13]
Hello, 

Thank you for developing so nice R package `alevinQC.`

what is the definition of `"cell barcode collapsing"` in elvinQC R package

What is the meaning of the following figure? 

Summay plot of cell barcode collapsing. Plot the original frequency of each cell barcode in the original  whitelist against the frequency after collapsing similar cell barcodes. 

Thanks in advance for any help! 

Best, 

Yue

![Screenshot from 2020-02-27 00-20-07](https://user-images.githubusercontent.com/40526984/75414608-158dc380-58f7-11ea-98f0-186ce8165792.png)

**Comment by csoneson** [comment]
Hi Yue,

thanks for using `alevinQC`. `Alevin` will first perform an initial whitelisting of barcodes (finding barcodes that are likely to represent cells). Afterwards, it will go through the remaining barcodes (that are present in lower frequencies) and determine for each of these whether the corresponding reads should be assigned to one of the whitelisted barcodes (e.g., if the observed barcode is likely to have resulted from a sequencing error in a whitelisted barcode), or discarded. This reassignment is what is visualized in the plot above. A more thorough description of the procedure is provided in the section "Initial whitelisting and barcode correction" in https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1670-y#Sec11.

**Comment by yueli8** [comment]
Hello, csoneson,

Thank you for detailed explanation!

Thank you again!

Best,

Yue
