### ISSUE TITLE
Input directory not compatible with Salmon v0.14 or newer (without external whitelist), the following required file(s) are missing or malformed:

### ISSUE THREAD

**Issue by PavanKhosla** [csoneson/alevinQC#17]
Hi @csoneson,

Would you happen to know why I am receiving the following error message?

Thank you!

Best,
Pavan

---------------------------
# Versions:
R - 4.0
alevinQC - 1.4.0
salmon - 1.3.0

---------------------------
# R code:
library(alevinQC)

setwd("C:/Users/pavan/Alevin/08_04/alevin_1k/")

alevinQCReport(baseDir = system.file("/alevin_output/alevin/", 
                                     package = "alevinQC"),
               sampleId = "alevin_test_full", 
               outputFile = "alevinReport.html", 
               outputFormat = "html_document",
               outputDir = "../", forceOverwrite = TRUE)

---------------------------
# Error Message:

Error in checkAlevinInputFiles(baseDir) : 
  Input directory not compatible with Salmon v0.14 or newer (without external whitelist), the following required file(s) are missing or malformed:
C:\Users\pavan\Documents\R\win-library\4.0\alevinQC/alevin/raw_cb_frequency.txt
C:\Users\pavan\Documents\R\win-library\4.0\alevinQC/alevin/featureDump.txt
C:\Users\pavan\Documents\R\win-library\4.0\alevinQC/aux_info/meta_info.json
C:\Users\pavan\Documents\R\win-library\4.0\alevinQC/aux_info/alevin_meta_info.json
C:\Users\pavan\Documents\R\win-library\4.0\alevinQC/cmd_info.json
C:\Users\pavan\Documents\R\win-library\4.0\alevinQC/alevin/whitelist.txt

Input directory not compatible with Salmon v0.14 or newer (with external whitelist), the following required file(s) are missing or malformed:
C:\Users\pavan\Documents\R\win-library\4.0\alevinQC/alevin/raw_cb_frequency.txt
C:\Users\pavan\Documents\R\win-library\4.0\alevinQC/alevin/featureDump.txt
C:\Users\pavan\Documents\R\win-library\4.0\alevinQC/aux_info/meta_info.json
C:\Users\pavan\Doc

---------------------------
# Alevin Code:
~/github.com/COMBINE-lab/salmon/releases/download/v1.3.0/salmon-latest_linux_x86_64/bin/salmon alevin -lISR -1 pbmc_1k_v2_fastqs/pbmc_1k_v2_S1_L001_R1_001.fastq.gz pbmc_1k_v2_fastqs/pbmc_1k_v2_S1_L002_R1_001.fastq.gz -2 pbmc_1k_v2_fastqs/pbmc_1k_v2_S1_L001_R2_001.fastq.gz pbmc_1k_v2_fastqs/pbmc_1k_v2_S1_L002_R2_001.fastq.gz --chromium -i index -p 32 -o alevin_output --tgMap txp2gene.tsv --dumpFeatures
---------------------------
# Data:
https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.0/pbmc_1k_v2

**Comment by csoneson** [comment]
It looks like a problem in the specification of the `baseDir` in the `alevinQC` call. Using `system.file` as you do above essentially tells R to look for the data inside the `alevinQC` package. Instead, just do `baseDir = "alevin_output"` to point `alevinQC` to the output directory.

**Comment by PavanKhosla** [comment]
Thank you so much!!!
