### ISSUE TITLE
suggestion to update ignorePandoc argument

### ISSUE THREAD

**Issue by LisaHagenau** [csoneson/alevinQC#19]
I had a problem generating the report with alevinQCReport(), with the error message "pandoc-citeproc is not available! The final report will not be generated.". I tried installing pandoc-citeproc with brew on MacOS Catalina, but this gave an error as well. Apparently, pandoc-citeproc is deprecated since pandoc version 2.11 (https://github.com/jgm/pandoc/releases/tag/2.11). 
Removing the .checkPandoc function and the ignorePandoc arguments in alevinQCReport.R and re-installing from source got rid of the error message and output the report. 
A better solution might be to update the .checkPandoc function: check the pandoc version and only checking for pandoc-citeproc for versions <2.11. 

Thanks!

**Comment by csoneson** [comment]
Thanks for the report! You are correct - I'll fix this.

**Comment by LisaHagenau** [comment]
Great, thank you!

**Comment by csoneson** [comment]
Sorry for the delay - would you be able to try the fix that I just pushed to the `master` branch of this repository, to see if that solves the problem for you?

**Comment by LisaHagenau** [comment]
Yes, it works fine now. Thank you!
