### ISSUE TITLE
error in alevin-fry summary

### ISSUE THREAD

**Issue by changostraw** [csoneson/alevinQC#32]
I get an error involving pandoc-citeproc when running:
`library(alevinQC)
alevinFryQCReport(
    mapDir = system.file("INS_PoolB_map/",
                         package = "alevinQC"),
    permitDir = system.file("INS_PoolB_quant/",
                            package = "alevinQC"),
    quantDir = system.file("INS_PoolB_quant_res/",
                           package = "alevinQC"),
    sampleId = "MT_alevin_INS_PoolB_rad", outputFile = "MT_alevin_INS_PoolB_rad.html",
    outputDir = tempdir("MT_alevin_INS_PoolB_rad/"), forceOverwrite = TRUE)` 

Error in .checkPandoc(ignorePandoc) : pandoc-citeproc is not available!

pandoc-citeproc is depreciated, however, I installed citeproc and tried again but still get the same error. 
Is there a work around you would suggest?
Thanks!

**Comment by csoneson** [comment]
Which version of `pandoc` do you have on your system? `pandoc-citeproc` should not be required for `pandoc` v2.11 and newer, so perhaps updating `pandoc` would be a solution. You can check if you have a version newer than 2.11 by 

```
rmarkdown::pandoc_available(version = "2.11")
```

The `pandoc` checking in `alevinQC` is performed by the internal function `.checkPandoc()`: https://github.com/csoneson/alevinQC/blob/825fa7c75fef65993244dc461fc09630a32b75a9/R/alevinQCReport.R#L18-L64. Perhaps running the commands of this function one by one can help you figure out why the R session is not picking up `pandoc-citeproc` properly. 

It is also possible to run `alevinFryQCReport()` setting `ignorePandoc=TRUE`, which will generate all the figures, but skip the final rendering of the report. 

Finally, just a question: `alevinQC` doesn't provide datasets named `INS_PoolB_map`, so I think your data paths should not involve the `system.file(..., package = "alevinQC")` part, but just point directly to the folders on your system (`system.file()` will look for the folders in the installation directory of `alevinQC`).
