### ISSUE TITLE
Release and upload to bioconda

### ISSUE THREAD

**Issue by Acribbs** [csoneson/alevinQC#5]
Hi,

This looks like a really useful tool and I would love to integrate this into my pipeline for evaluating alevin output. I was just wondering how far off this project was from having its first release?  Also, it would be great if this could be packaged in bioconda.

Thanks

**Comment by csoneson** [comment]
Hello! The package is in fact already released, as part of Bioconductor (https://bioconductor.org/packages/alevinQC/, see the README for installation instructions). As a consequence, it is also packaged in bioconda: https://bioconda.github.io/recipes/bioconductor-alevinqc/README.html

**Comment by Acribbs** [comment]
Hi Sorry I completely missed this, I was looking at the devel version: https://bioconductor.org/packages/devel/bioc/html/alevinQC.html and also didn't see the bioconda package.

Thanks very much.
