### ISSUE TITLE
number of CB in whitelist does not match output files

### ISSUE THREAD

**Issue by Ryan-Zhu** [csoneson/alevinQC#7]
[AD2.zip](https://github.com/csoneson/alevinQC/files/3284421/AD2.zip)
Hello,

I ran alevinqc_1.1.1 in R3.6 on the output files generated by Alevin-Salmon 0.14.0.  I did not supply a whitelist to Alevin.

The QC report showed **1277 Number of barcodes in initial whitelist** and **648 Number of barcodes in final whitelist**. However, according to the run files generated by Alevin (featureDump.txt and whitelist.txt), these number should be **1602** and **647**. Can you look into this? 

Output files attached. Thank you.

**Comment by csoneson** [comment]
Thanks for your message. As far as I can see in your attached report, the number of barcodes in the final whitelist is indeed correctly identified to be 647. The number of barcodes in the initial whitelist should be compared to the `initial_whitelist ` value in the `alevin_meta_info.json` file - could you check what this number is?

**Comment by Ryan-Zhu** [comment]
Thank you for your prompt response.

Please see below file content in `alevin_meta_info.json` . Note final whitelist number in the report is off by 1 (**648** reported). **1602** is also the CB number in the output file `quants_mat.mtx.gz` , shouldn't it be the correct initial whitelist number?  Thank you.

    "total_reads": 38822848,
    "reads_with_N": 9413,
    "noisy_cb_reads": 24866100,
    "noisy_umi_reads": 638,
    "used_reads": 13946059,
    "mapping_rate": 3.9311438460156244,
    "reads_in_eqclasses": 1526182,
    "total_cbs": 1785900,
    "used_cbs": 20514,
    "initial_whitelist": 1277,
    "low_conf_cbs": 638,
    "num_features": 6,
    "final_num_cbs": 647,
    "deduplicated_umis": 391074,
    "mean_umis_per_cell": 604,
    "mean_genes_per_cell": 431

**Comment by csoneson** [comment]
I'm sorry, but I can't see the number 648 in the report you sent above (the "Final whitelist" table says 647). As for the initial whitelist, Alevin reports 1,277 cells (as seen in your file), defined by the first knee cutoff; these will be retained as-is (not sequence corrected). Alevin also includes additional "low-confidence" cells in the initial quantification step, which is what you see in `quants_mat.mtx.gz`. Perhaps @k3yavi can clarify further.

**Comment by Ryan-Zhu** [comment]
Are you saying the html report shows 647 in Final whitelist? This is bizarre. See screenshot attached.
<img width="360" alt="Capture" src="https://user-images.githubusercontent.com/6526590/59410267-46c86280-8d6d-11e9-9d82-427280476d12.PNG">

And for initial whitelist, I referenced what you explained back to the Alevin paper and I think I understand it now. Thank you!

**Comment by csoneson** [comment]
Yes, this is what I see:
<img width="450" alt="Screen Shot 2019-06-13 at 08 56 21" src="https://user-images.githubusercontent.com/5628952/59410456-2faf6200-8db9-11e9-8bbe-f5a8effc909b.png">

**Comment by Ryan-Zhu** [comment]
Sorry, I ran Alevin twice on the same sample and I messed up the two reports. You are right and thank you again. Closing now!
