### ISSUE TITLE
All alevin flags needed to run alevinQC?

### ISSUE THREAD

**Issue by jdrnevich** [csoneson/alevinQC#8]
Hi @csoneson ! I was excited to find the alevinQC package because we are looking to replace Cell Ranger with salmon/alevin for our production work and also need a replacement for the web_summary.html file. However, I cannot get alevinQC to run because I'm missing 2-3 of the output files. I had first run salmon alevin (v0.14.1) with the minimum input parameters and got:

`> checkAlevinInputFiles(baseDir = "Control")
Error in checkAlevinInputFiles(baseDir = "Control") :
  The following required file(s) are missing:
Control/alevin/raw_cb_frequency.txt
Control/alevin/filtered_cb_frequency.txt
Control/alevin/MappedUmi.txt
`
Then based on the alevinQC vignette I added the `--dumpFeatures` flag but I am still missing two files:

`> checkAlevinInputFiles(baseDir = "Control")
Error in checkAlevinInputFiles(baseDir = "Control") :
  The following required file(s) are missing:
Control/alevin/filtered_cb_frequency.txt
Control/alevin/MappedUmi.txt
`

I can't figure out from the alevin documentation what flags I need to add to get these output files. Thanks!

**Comment by csoneson** [comment]
Hi - which version are you using (you currently need the devel version for reading output from salmon >= 0.14)?

**Comment by jdrnevich** [comment]
We are using the release version alevinQC_1.0.0. I’m not sure I’ll be able to get the devel version of BioC and alevinQC installed on our computer cluster because the group that controls it barely lets me request upgrading R once per year! I’ll try running the release version of alevinQC on output from salmon 0.13.1 for now. May I suggest you added compatible salmon version information in the alevinQC vignette? I heard from Avi that salmon is also coming out with a new release soon.

Thanks!

**Comment by csoneson** [comment]
Yep, I’ll make that clearer (currently it’s only a note in the README). Thanks!

**Comment by apeltzer** [comment]
Had the same issue just now - could you not push a minor new release that addresses this issue?

**Comment by csoneson** [comment]
Hi @apeltzer - sorry, I missed your message. Porting the code for allowing Salmon >=0.14 output is, in my opinion, more than a bug fix, and thus not really something I would like to add to the current Bioconductor release version. The next release will be in about a month, and it will all be included there. 
Until then, while I haven't tested it extensively, you could probably install the current GitHub version though, it should not conflict with the release Bioc.

**Comment by vertesy** [comment]
Hey,

I have the same problem with alevinQC (v 1.2 or 1.3) after mapping with salmon alevin (v0.14.1).  

Some files are indeed not there ("raw_cb_frequency"), but alevin did not threw an error,  plus the output files look good, based on [Alevin/Seurat](https://combine-lab.github.io/alevin-tutorial/2018/alevin-seurat/). 

##### Content of baseDir:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/5101911/68761050-87c1ed00-0613-11ea-8039-aa92f00923dd.png">


### The commands:
```R
baseDir <- system.file("~/101146.pc25/", package = "alevinQC")
checkAlevinInputFiles(baseDir = baseDir)

```
### The error:
```R
Error in checkAlevinInputFiles(baseDir) : 
  Input directory not compatible with Salmon v0.14, the following required file(s) are missing or malformed:
/alevin/raw_cb_frequency.txt
/alevin/featureDump.txt
/alevin/whitelist.txt
/aux_info/meta_info.json
/aux_info/alevin_meta_info.json
/cmd_info.json

Input directory not compatible with Salmon pre-v0.14, the following required file(s) are missing or malformed:
/alevin/raw_cb_frequency.txt
/alevin/filtered_cb_frequency.txt
/alevin/featureDump.txt
/alevin/MappedUmi.txt
/alevin/whitelist.txt
/alevin/quants_mat_rows.txt
/alevin/quants_mat_cols.txt
/alevin/quants_mat.gz
/aux_info/meta_info.json
/cmd_info.json

Warning:
In normalizePath(baseDir) : path[1]="": No such file or directory
```

### Install from bioconductor (v1.2)
```R
if (F) {
  if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
  BiocManager::version()
  BiocManager::install(version="3.10")
  BiocManager::install("alevinQC")
}
require(alevinQC)
sessioninfo::session_info()
```
### Install from github (v1.3)
```R
if (F) {
    library(devtools)
    install_github("csoneson/alevinQC")

}
```

**Comment by csoneson** [comment]
This looks strange:
```
baseDir <- system.file("~/101146.pc25/", package = "alevinQC")
```
This command will tell `R` to look in the `alevinQC` package directory, and try to find the indicated folder. If this is a folder on your computer, you should just do 
```
baseDir <- "~/101146.pc25/"
```

**Comment by vertesy** [comment]
Thanks for getting back!

This line of code comes from the [BioConductor](http://master.bioconductor.org/packages/devel/bioc/vignettes/alevinQC/inst/doc/alevinqc.html) page:
<img width="689" alt="image" src="https://user-images.githubusercontent.com/5101911/68773606-29edcf00-062c-11ea-85b6-6d1daf13d1d4.png">
(And I also wondered, what it does, given `?system.file`)

When I manually set it to `checkAlevinInputFiles(baseDir = "[...]/101147")`, I got:

```R
Error in checkAlevinInputFiles(baseDir = "[...]/101147") : 
  Input directory not compatible with Salmon v0.14, the following required file(s) are missing or malformed:
[...]/101147/alevin/rawcb_frequency.txt

Input directory not compatible with Salmon pre-v0.14, the following required file(s) are missing or malformed:
[...]/101147/alevin/raw_cb_frequency.txt
[...]/101147/alevin/filtered_cb_frequency.txt
[...]/101147/alevin/MappedUmi.txt
````

And  
```R
> outputDir <- tempdir()
> alevinQCReport(baseDir = baseDir, sampleId = "testSample",
+                outputFile = "alevinReport.html",
+                outputFormat = "html_document",
+                outputDir = outputDir, forceOverwrite = TRUE)
Error in in checkAlevinInputFiles(baseDir) : 
  Input directory not compatible with Salmon v0.14, the following required file(s) are missing or malformed:
[...]/101147/alevin/raw_cb_frequency.txt

Input directory not compatible with Salmon pre-v0.14, the following required file(s) are missing or malformed:
[...]/101147/alevin/raw_cb_frequency.txt
[...]/101147/alevin/filtered_cb_frequency.txt
[...]/101147/alevin/MappedUmi.txt

```

**Comment by csoneson** [comment]
Yes, in the Bioconductor vignette we read the example data that is provided with the package (which is indeed stored in the `alevinQC` package directory), so that's all fine. To use your own data, you need to point to the folder where your data lives. 

Now, for the missing `raw_cb_frequency.txt`, did you specify the `--dumpFeatures` flag when running `alevin`? See e.g. here: https://csoneson.github.io/alevinQC/articles/alevinqc.html#assumed-output-directory-structure

**Comment by vertesy** [comment]
Thanks, that must be it! ( I did not specify the `--dumpFeatures` flag )

**Comment by csoneson** [comment]
I'll close this issue now - feel free to reopen if the problem persists.
