### ISSUE TITLE
Report lacks fonts?

### ISSUE THREAD

**Issue by apeltzer** [csoneson/alevinQC#9]
Hi @csoneson !

Thanks for the tool - I figured out how to run it and all things seem to work just fine. However, I'm experiencing plots like this, without any fonts (?):

<img width="754" alt="Bildschirmfoto 2019-12-02 um 19 43 08" src="https://user-images.githubusercontent.com/2359510/69985705-10111f00-153c-11ea-8eba-d554505130b8.png">

Any idea if there is a missing dependency of the pipeline to plot these plots properly? 

Thank you in advance,

Alex

**Comment by csoneson** [comment]
Oh wow, I've never seen this...could you post your session info?

**Comment by apeltzer** [comment]
Of course - just rename the `.txt` to `html` only (Github doesn't allow html directly). This is based on the workflow we're building at the moment over at https://github.com/nf-core/scrnaseq. 
[alevinReport.html.txt](https://github.com/csoneson/alevinQC/files/3913045/alevinReport.html.txt)

**Comment by apeltzer** [comment]
Probably related to something like this I fear: https://github.com/conda-forge/r-base-feedstock/issues/91

**Comment by apeltzer** [comment]
I'm giving this a try by adding the `- font-ttf-source-code-pro=2.030` to my `environment.yml` file. 

Yeah, after adding this - things are fine for me :-)

**Comment by csoneson** [comment]
Great! This is good to know, thanks for the report (and the solution :)).

**Comment by apeltzer** [comment]
Of course, thanks for the tool (and the rapid responses!)
